#description = "This is an example site"
#author = "That Person"
#shortName = "Person"

############## GOOGLE ##############
#[google]
#siteVerificationId = "BLAHBLAHBLAHBLAH"
#analyticsId = "UA-XXXXXXX-X"

############## BANNER ##############
#[banner]
#message = "Black Lives Matter."
#link = "https://blacklivesmatter.com"
#cta = "Make a difference."

############## SOCIAL MEDIA ##############
#[[social]]
#title = "Twitter"
#icon = "fa-twitter"
#link = "https://twitter.com/twitter"

